#!/bin/csh
#PBS -A gfdl_o
#PBS -N eady
#PBS -l size=1
#PBS -l walltime=15:30:00

module unload PrgEnv-intel
module load PrgEnv-pgi
module load cray-netcdf

cd /lustre/f1/$USER
cd LR_original
cp ~Elizabeth.Yankovsky/MITgcm_c65t/verification/KaraSea_parameterspace/LR_original/input/* .

aprun -n 32 ./mitgcmuv


